language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"

services:
  - mongodb
  - redis-server

install:
  - "pip install --upgrade ."
  - "pip install --upgrade -r requirements-test.txt"

script: py.test -s -v tests
