language: python
sudo: false
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

services:
  - mongodb
  - redis-server

install:
  - pip install --upgrade .
  - pip install --upgrade -r requirements-test.txt
  - pip install coveralls

script: py.test -s -v tests --cov request_cache

after_success:
  coveralls
