language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

services:
  - mongodb
  - redis-server

install:
  - pip install --upgrade .
  - pip install --upgrade -r requirements-test.txt
  - pip install coveralls==1.1

script: pytest -s -v tests --cov requests_cache

after_success:
  coveralls
